# Generated by Django 5.2.7 on 2025-10-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='A short description of the artwork.', null=True)),
                ('image', models.ImageField(upload_to='gallery_images/')),
                ('category', models.CharField(choices=[('MURAL', 'Mural'), ('POTTERY', 'Pottery')], default='MURAL', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Gallery Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
