# Generated by Django 5.2.7 on 2025-10-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(help_text='A unique URL-friendly version of the title.', max_length=200, unique=True)),
                ('summary', models.TextField(help_text='A short summary for the services overview page.')),
                ('detailed_description', models.TextField(help_text="The full description for the service's dedicated page.")),
                ('image', models.ImageField(blank=True, help_text='An image representing the service.', null=True, upload_to='service_images/')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
