# Generated by Django 5.2.7 on 2025-10-15 21:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='detailed_description',
            field=ckeditor.fields.RichTextField(help_text="The full description for the service's dedicated page."),
        ),
    ]
