# Generated by Django 5.2.7 on 2025-10-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author_name', models.CharField(max_length=100)),
                ('company_or_title', models.CharField(blank=True, help_text="e.g., 'Homeowner' or 'CEO of Cafe Name'", max_length=100, null=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Only approved testimonials will be shown on the site.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
